const List<String> championShip = [
  "بطوله الف تيم",
  "الكاس",
  'الدوري الكلاسيكي',
  "Vip",
];
List<String> names = [
  "NebulaRise",
  "ضوء القمر",
  "AeroWave",
  "أرواح المدينة",
  "PrimeEcho",
  "نجوم الصباح",
  "AlphaStrum",
  "ظلال الصحراء",
  "BetaBlast",
  "صدى الأمواج",
  "CrescendoCore",
  "مرايا الزمان",
  "DeltaDawn",
  "EchoEssence",
  "نسيم الفجر",
  "FrostFire",
  "أغنية الغروب",
  "GaleGlow",
  "سراب الصحراء",
  "HaloHaven",
  "شروق جديد",
  "IllusionInk",
  "أصداء الجبال",
  "JungleJewel",
  "تأمل الليل",
  "KarmaKnot",
  "لحن الحياة",
  "LumenLore",
  "موجة هادئة",
  "MysticMind",
  "رقص النسمات",
  "NovaNectar",
  "صوت السماء",
  "OrionOrbit",
  "وهج النجوم",
  "PulsePhoenix",
  "نغم الأمل",
  "QuantumQuest",
  "شجر السنديان",
  "RiftRipple",
  "ليلة هادئة",
  "SolarSong",
  "وميض الفضاء",
  "TerraTune",
  "أحلام الظل",
  "UltraUtopia",
  "فراشة الليل",
  "VividVault",
  "شعاع السحاب",
  "WhisperWind",
  "رحلة الرياح",
  "XanaduXeno",
  "قلب الصحراء",
  "YonderYarn",
  "أغنية المطر",
  "ZenithZephyr",
  "AbyssAura",
  "زهرة الليل",
  "BlazeBlessing",
  "نسمات الصباح",
  "CosmicChorus",
  "رداء السحاب",
  "DreamDew",
  "شفق البحر",
  "EtherEra",
  "غموض الصحراء",
  "FableFlow",
  "نجمة الفجر",
  "GlowGrace",
  "ريشة النسر",
  "HarmonyHaze",
  "صوت الصمت",
  "InfernoInk",
  "لحن الواحات",
  "JourneyJade",
  "مهرجان الليل",
  "KineticKiss",
  "طيف الأمل",
  "LunarLyric",
  "قمر الشتاء",
  "MomentumMist",
  "غناء الساحرة",
  "NectarNova",
  "رياح الجنوب",
  "OrbitOasis",
  "ومضة الفجر",
  "PulsePetal",
  "صدى الصدفة",
  "QuartzQuiver",
  "شجر النخيل",
  "RippleRealm",
  "رقصة الظل",
  "SonicStar",
  "ألوان الريف",
  "TidalTruth",
  "موج البحر",
  "UltraUnity",
  "نسيم الغروب",
  "VertexVerve",
  "وحي الشاعر",
  "WhirlWhisper",
  "أضواء الجنة",
  "XposeXeno",
  "حبل السماء",
  "YieldYonder",
  "حكاية الرمل",
  "ZenZone",
  "طيف القمر",
  "HorizonHeart",
  "خطى القدر",
  "InkIllusion",
  "زهرة السراب",
  "JasperJubilee",
  "غناء الطيور",
  "أسطورة الخيال",
  "LunarLantern",
  "موجات النسيم",
  "MysticMingle",
  "قلب الليل",
  "NobleNest",
  "أماني المحيط",
  "OrchidOrbit",
  "ألوان الشروق",
  "PioneerPulse",
  "نسمة الصباح",
  "QuestQuartz",
  "حكاية الأوتار",
  "RadiantRift",
  "أنغام الرياح",
  "StellarStream",
  "سحر الصحراء",
  "TerraTwilight",
  "قوس قزح الليل",
  "UpliftUniverse",
  "رقصة الوتر",
  "VividVoyage",
  "مرسى الأماني",
  "WhirlwindWhisper",
  "سفراء السماء",
  "XenonXanadu",
  "لحظات الزمان",
  "نجمة الشمال",
  "لغة النجوم",
  "AstralArt",
  "أمواج الوقت",
  "BlazeBloom",
  "مدينة الألوان",
  "CosmicCraft",
  "نسيم الجبال",
  "DuneDance",
  "وتر الحنين",
  "EonEcho",
  "طيف الغروب",
  "FrostFlame",
  "مغامرة النسمات",
  "غناء الوادي",
  "HarmonyHaven",
  "أمواج البحر",
  "InfernoIris",
  "لحن الليل",
  "JewelJazz",
  "مرسى الأحلام",
  "KiteKnight",
  "وحي الصمت",
  "LagoonLullaby",
  "MajestyMingle",
  "رحلة الروح",
  "NovaNest",
  "موجة الوفاء",
  "OpalOrbit",
  "أغنية القلب",
  "غناء الأقدار",
  "QuasarQuest",
  "ومضة الذكريات",
  "سراب الليل",
  "SilkSonic",
  "زهرة الغموض",
  "TwilightTerra",
  "أرواح الوادي",
  "UtopiaUltra",
  "موجة الصمت",
  "VerveVivid",
  "غناء السماء",
  "WhimsyWave",
  "رقصة الأمواج",
  "عشق المحيط",
  "لغة الرياح",
  "وتر الحياة",
  "AlphaArt",
  "أغنية الحرية",
  "BloomBlaze",
  "نسمة الأمل",
  "ChorusCraft",
  "ظلال الوقت",
  "DanceDune",
  "حروف السماء",
  "EchoEon",
  "نجمة الزمان",
  "FlameFrost",
  "رياح الصحراء",
  "GlowGale",
  "صدى الأقدار",
  "HavenHarmony",
  "نسيم الجنة",
  "IrisInferno",
  "رحلة الصوت",
  "JazzJewel",
  "أمواج الشوق",
  "KnightKite",
  "ألوان الغروب",
  "LullabyLagoon",
  "حكاية الروح",
  "MingleMajesty",
  "نسمة الأماني",
  "NestNova",
  "لغة الأحلام",
  "OrbitOpal",
  "حب الحياة",
  "PulsePioneer",
  "رقصة الفجر",
  "QuestQuasar",
  "وحي القلب",
  "RealmRipple",
  "أغنية الصحراء",
  "SonicSilk",
  "زمردة الوادي",
  "صدى المحيط",
  "غناء السكون",
  "VividVerve",
  "أرواح الليل",
  "WaveWhimsy",
  "نغم الوتر",
  "XenoXpose",
  "سمفونية الروح",
  "YonderYield",
  "وتر الغروب",
  "ZephyrZenith",
  "رحلة النجوم",
  "ArtAlpha",
  "أصداء الأمل",
  "حروف الغموض",
  "CraftChorus",
  "محارب",
  "نجم",
  "أسد",
  "صقر",
  "رياح",
  "ألماس",
  "شمس",
  "قمر",
  "بحار",
  "جبل",
  "نهر",
  "شجرة",
  "سماء",
  "رمل",
  "زهرة",
  "قلعة",

];

List<String> arabCountrys = [
  "مصر",
  "السعودية",
  "الإمارات",
  "الكويت",
  "البحرين",
  "العراق",
  "الأردن",
  "لبنان",
  "سوريا",
  "فلسطين",
  "اليمن",
  "السودان",
  "ليبيا",
  "تونس",
  "الجزائر",
  "المغرب",
  "موريتانيا",
  "قطر",
  "عمان",
  "جيبوتي",
  "الصومال",
  "جزر القمر",
];
