// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMF0UE3YvbPHQ3SGs5leKTRnrghu60OPU',
    appId: '1:64139383562:web:3be7fcffd3be7ebb8aa0f3',
    messagingSenderId: '64139383562',
    projectId: 'crazy-fantasy-97ec8',
    authDomain: 'crazy-fantasy-97ec8.firebaseapp.com',
    storageBucket: 'crazy-fantasy-97ec8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV8aTgaP0AW33VBCi76-bSvBAMoNDuCPk',
    appId: '1:64139383562:android:5ce6f7cf1e2c08268aa0f3',
    messagingSenderId: '64139383562',
    projectId: 'crazy-fantasy-97ec8',
    storageBucket: 'crazy-fantasy-97ec8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ34JhqvfCcZ_BhNT4xaEbOCt2W7YGxDc',
    appId: '1:64139383562:ios:c0065eb92d45c0f08aa0f3',
    messagingSenderId: '64139383562',
    projectId: 'crazy-fantasy-97ec8',
    storageBucket: 'crazy-fantasy-97ec8.appspot.com',
    iosClientId: '64139383562-jv06l1lh5lfjt0sejcgsj8e3kpinr9k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.crazyFantasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ34JhqvfCcZ_BhNT4xaEbOCt2W7YGxDc',
    appId: '1:64139383562:ios:ebb23b32e22b01988aa0f3',
    messagingSenderId: '64139383562',
    projectId: 'crazy-fantasy-97ec8',
    storageBucket: 'crazy-fantasy-97ec8.appspot.com',
    iosClientId: '64139383562-c5tnfrvaknp5a7h43ae78vpgk66obbes.apps.googleusercontent.com',
    iosBundleId: 'com.example.crazyFantasy.RunnerTests',
  );
}
